import { SIM_COUNT } from '../config';

/** One hundred local opponents. Online rooms still use the server's names. */
export const DEEP_SEA_NAMES: readonly string[] = [
  'kelpy',
  'coral bell',
  'sir finsley',
  'brine baby',
  'blub blub',
  'whirlpool',
  'captain kelp',
  'lady lagoon',
  'tin tuna',
  'servo shrimp',
  'tide song',
  'miss minnow',
  'bolt barnacle',
  'pixel puffer',
  'the codfather',
  'watt a whale',
  'gill loose',
  'robo ray',
  'clank clam',
  'zippy eel',
  'mama manatee',
  'chip chela',
  'drone dolphin',
  'reefpresso',
  'sir swimalot',
  'boatato chip',
  'whirlpup',
  'lady bugfish',
  'tin limpet',
  'kelpworth jr',
  'data daisyfish',
  'blink bass',
  'jammer clam',
  'pearlina',
  'dot dot dab',
  'bloop bloop',
  'tunnel tuna',
  'house herring',
  'elroy eel',
  'cruise carp',
  'scatter skate',
  'chase chub',
  'fright fish',
  'eye sea you',
  'jam on kelp',
  'pressure perch',
  'stack anemone',
  'side reef sam',
  'mini reef',
  'panel pearl',
  'red mine',
  'pale urchin',
  'slow poke seal',
  'reef boss',
  'clearcurrent',
  'last bubble',
  'one oh foam',
  'fin and soul',
  'nautilus nell',
  'tensor tuna',
  'gradient gill',
  'overfit otter',
  'epoch eel',
  'batch beluga',
  'token turtle',
  'prompt prawn',
  'halluci-ray',
  'tide tom',
  'tide pip',
  'vortex vince',
  'cosine coral',
  'kernel kelp',
  'softmax sole',
  'relu ray',
  'dropout dory',
  'bias beluga',
  'checkpoint crab',
  'fine-tune fin',
  'zero-shot zoa',
  'rag doll ray',
  'widget wahoo',
  'gizmo guppy',
  'sprocket squid',
  'anemone andy',
  'cyborg conch',
  'droid dolphin',
  'mech marlin',
  'piston pike',
  'rivet ray',
  'solder salmon',
  'toggle tuna',
  'urchin ursula',
  'current cory',
  'wave willy',
  'xray xavier',
  'yaml yellowtail',
  'zip tide zed',
  'barnacle bob',
  'eliza eel',
  'clippy crab',
];

if (DEEP_SEA_NAMES.length !== SIM_COUNT) {
  throw new Error(`expected ${SIM_COUNT} deep sea names, found ${DEEP_SEA_NAMES.length}`);
}
if (new Set(DEEP_SEA_NAMES.map((name) => name.toLowerCase())).size !== DEEP_SEA_NAMES.length) {
  throw new Error('deep sea names must be unique');
}
